import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

import { twMerge } from "tailwind-merge"
import NavBar from "./navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={twMerge(inter.className, "relative bg-white text-black dark:bg-black dark:text-white")}>
        <header className="bg-blue-600 text-white shadow-md">
          <NavBar />
        </header>
        <main className="lg:p-0 mx-auto max-w-7xl">{children}</main>
      </body>
    </html>
  )
}
